<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>NetWatch</AssemblyName>
    <RootNamespace>NetWatch.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.4.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetWatch.Core\NetWatch.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- 避免与 WPF 的 Application 类型冲突 -->
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>
</Project>
